<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="xunit" />
    <PackageReference Include="Xunit.SkippableFact" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\apps\Korat.Cloud\Korat.Cloud.csproj" />
    <ProjectReference Include="..\..\apps\Korat.Cli\Korat.Cli.csproj" />
    <ProjectReference Include="..\..\src\Korat.Protocol\Korat.Protocol.csproj" />
    <ProjectReference Include="..\Korat.Cloud.IntegrationTests\Korat.Cloud.IntegrationTests.csproj" />
  </ItemGroup>

</Project>
