// <auto-generated />
using System;
using Korat.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Korat.Persistence.Migrations
{
    [DbContext(typeof(KoratDbContext))]
    [Migration("20260527200329_AddStatusStringConversionAndPendingIndex")]
    partial class AddStatusStringConversionAndPendingIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-preview.2.25163.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Korat.Persistence.AccessRequestRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("AgentClientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("McpServerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PublisherNodeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestedByNodeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResolvedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("SpaceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("SpaceId", "AgentClientId", "McpServerId")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'Pending'");

                    b.ToTable("AccessRequests");
                });

            modelBuilder.Entity("Korat.Persistence.AgentClientRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NodeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SpaceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("AgentClients");
                });

            modelBuilder.Entity("Korat.Persistence.CryptoSessionRecord", b =>
                {
                    b.Property<string>("SessionId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SessionId");

                    b.ToTable("CryptoSessions");
                });

            modelBuilder.Entity("Korat.Persistence.GrantRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("AgentClientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApprovedByUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedFromAccessRequestId")
                        .HasColumnType("text");

                    b.Property<string>("McpServerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevokedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("SpaceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("AgentClientId", "McpServerId", "Status");

                    b.ToTable("Grants");
                });

            modelBuilder.Entity("Korat.Persistence.McpServerRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LaunchArguments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LaunchCommand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PublisherNodeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SpaceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Transport")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SpaceId", "DisplayName")
                        .IsUnique();

                    b.ToTable("McpServers");
                });

            modelBuilder.Entity("Korat.Persistence.NodeRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentGatewayId")
                        .HasColumnType("text");

                    b.Property<string>("DeviceFingerprint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SpaceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SpaceId", "DisplayName");

                    b.ToTable("Nodes");
                });

            modelBuilder.Entity("Korat.Persistence.SessionRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("AgentClientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("BytesClientToServer")
                        .HasColumnType("bigint");

                    b.Property<long>("BytesServerToClient")
                        .HasColumnType("bigint");

                    b.Property<string>("ClientNodeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CloseReason")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GrantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HomeGatewayId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LargeTransferWarning")
                        .HasColumnType("boolean");

                    b.Property<string>("McpServerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PublisherNodeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SpaceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Korat.Persistence.SpaceRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Spaces");
                });
#pragma warning restore 612, 618
        }
    }
}
