<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.Orleans.TestingHost" />
    <PackageReference Include="Microsoft.Orleans.Serialization.SystemTextJson" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="NATS.Net" />
    <PackageReference Include="NATS.NKeys" />
    <PackageReference Include="Testcontainers" />
    <PackageReference Include="Testcontainers.Nats" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.Net.Client" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\apps\Korat.Cloud\Korat.Cloud.csproj" />
    <ProjectReference Include="..\..\src\Korat.Domain\Korat.Domain.csproj" />
    <ProjectReference Include="..\..\src\Korat.Grains\Korat.Grains.csproj" />
    <ProjectReference Include="..\..\src\Korat.Persistence\Korat.Persistence.csproj" />
    <ProjectReference Include="..\..\src\Korat.Protocol\Korat.Protocol.csproj" />
  </ItemGroup>

</Project>
