<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Testcontainers.Nats" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="Xunit.SkippableFact" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Korat.Domain\Korat.Domain.csproj" />
    <ProjectReference Include="..\..\src\Korat.Persistence\Korat.Persistence.csproj" />
    <ProjectReference Include="..\..\apps\Korat.Cloud\Korat.Cloud.csproj" />
  </ItemGroup>

</Project>
